# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-04 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog02', '0002_auto_20180504_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
